import test from 'node:test'; import assert from 'node:assert/strict';
import { createDb } from '../src/db.js'; import { createApp } from '../src/app.js';

async function fixture(t){const db=createDb(':memory:'), cfg={allowedOrigins:new Set(['http://localhost:5173']),sessionTtlMs:3600000,trustProxy:false};const app=createApp({db,config:cfg,now:()=>Date.UTC(2026,6,13)}), server=app.listen(0);await new Promise(r=>server.once('listening',r));t.after(()=>{server.close();db.close()});const base=`http://127.0.0.1:${server.address().port}`;return async(path,opt={})=>fetch(base+path,{...opt,headers:{'content-type':'application/json',...opt.headers}})}
async function account(call){await call('/api/auth/register',{method:'POST',body:JSON.stringify({email:'player@example.com',password:'correct horse battery',displayName:'Player'})});const r=await call('/api/auth/login',{method:'POST',body:JSON.stringify({email:'player@example.com',password:'correct horse battery'})});return (await r.json()).token}
test('register, login, protected profile and logout',async t=>{const call=await fixture(t),token=await account(call);let r=await call('/api/profile',{headers:{authorization:`Bearer ${token}`}});assert.equal(r.status,200);assert.equal((await r.json()).user.displayName,'Player');r=await call('/api/auth/logout',{method:'POST',headers:{authorization:`Bearer ${token}`}});assert.equal(r.status,204);r=await call('/api/profile',{headers:{authorization:`Bearer ${token}`}});assert.equal(r.status,401)});
test('registration returns an immediately usable session',async t=>{const call=await fixture(t),r=await call('/api/auth/register',{method:'POST',body:JSON.stringify({email:'new@example.com',password:'correct horse battery',displayName:'New Player'})}),body=await r.json();assert.equal(r.status,201);assert.ok(body.token);const p=await call('/api/profile',{headers:{authorization:`Bearer ${body.token}`}});assert.equal(p.status,200);assert.equal((await p.json()).user.displayName,'New Player')});
test('favorites, recents and validation',async t=>{const call=await fixture(t),token=await account(call),h={authorization:`Bearer ${token}`};assert.equal((await call('/api/favorites/slots-royal',{method:'PUT',headers:h})).status,204);assert.equal((await call('/api/recents/slots-royal',{method:'POST',headers:h})).status,204);assert.equal((await call('/api/recents/bad%20game',{method:'POST',headers:h})).status,400);assert.equal((await (await call('/api/favorites',{headers:h})).json()).games[0].gameId,'slots-royal')});
test('daily reward is idempotent and ledger immutable',async t=>{const call=await fixture(t),token=await account(call),h={authorization:`Bearer ${token}`};let a=await (await call('/api/wallet/daily-reward',{method:'POST',headers:h})).json(),b=await (await call('/api/wallet/daily-reward',{method:'POST',headers:h})).json();assert.equal(a.claimed,true);assert.equal(b.claimed,false);assert.equal(b.balance,1250)});
test('CORS only permits configured origin',async t=>{const call=await fixture(t);let r=await call('/health',{headers:{origin:'http://localhost:5173'}});assert.equal(r.headers.get('access-control-allow-origin'),'http://localhost:5173');r=await call('/health',{headers:{origin:'https://evil.test'}});assert.equal(r.headers.get('access-control-allow-origin'),null)});
