import React,{useEffect,useState}from'react';import{X,Gift,LogOut,UserRound,Heart,History,ShieldCheck,Settings,Shield}from'lucide-react';import{api}from'./api';import{track}from'./analytics';import{verifyRoundProof}from'./fairness';import{AccountSettings}from'./AccountSettings';import{ResponsiblePlay,ResponsibleCheckBanner}from'./ResponsiblePlay';import OauthButtons from'./OauthButtons';import{useT}from'./i18n';import'./profile-stats.css';import'./personalization.css';import'./history.css';

function FairnessProof({round}){const[result,setResult]=useState(null),short=x=>x?`${x.slice(0,10)}…${x.slice(-6)}`:'Not revealed';const verify=async()=>setResult(await verifyRoundProof(round));return <details className="fairnessProof"><summary><ShieldCheck/> Verify fairness</summary><dl><div><dt>Commitment</dt><dd title={round.serverSeedHash}>{short(round.serverSeedHash)}</dd></div><div><dt>Revealed seed</dt><dd title={round.serverSeed}>{short(round.serverSeed)}</dd></div><div><dt>Client seed</dt><dd title={round.clientSeed}>{short(round.clientSeed)}</dd></div><div><dt>Nonce</dt><dd>{round.nonce}</dd></div></dl><button type="button" onClick={verify} disabled={!round.serverSeed}>Recalculate in browser</button>{result&&<p className={result.verified?'proofOk':'proofBad'} role="status">{result.verified?'Commitment verified':result.reason}{result.digest&&<small title={result.digest}> HMAC {short(result.digest)}</small>}</p>}</details>}
export default function AccountPanel({onClose,onUser}){
  const t=useT();
  const[mode,setMode]=useState(api.hasSession()?'profile':'register'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[displayName,setDisplayName]=useState(''),[user,setUser]=useState(null),[wallet,setWallet]=useState(null),[favorites,setFavorites]=useState([]),[recents,setRecents]=useState([]),[rounds,setRounds]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[rewardDone,setRewardDone]=useState(false),[onSettings,setOnSettings]=useState(false),[onResp,setOnResp]=useState(false);
 const load=async()=>{try{const[p,w]=await Promise.all([api.profile(),api.wallet()]);setUser(p.user);setWallet(w);setMode('profile');setRewardDone(w.ledger?.some(x=>x.idempotencyKey===`daily:${new Date().toISOString().slice(0,10)}`));const[f,r,h]=await Promise.allSettled([api.favorites(),api.recents(),api.history()]);const fs=f.status==='fulfilled'?f.value.games:[],rs=r.status==='fulfilled'?r.value.games:[],hs=h.status==='fulfilled'?h.value.rounds:[];setFavorites(fs);setRecents(rs);setRounds(hs);onUser?.(p.user,{favorites:fs,recents:rs})}catch(e){if(e.message==='unauthorized')setMode('login');else setError('Profile temporarily unavailable. Please retry.')}};
 useEffect(()=>{if(api.hasSession())load()},[]);
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const r=mode==='register'?await api.register({email,password,displayName}):await api.login({email,password});setUser(r.user);setMode('profile');await load()}catch(e){setError(e.message.replaceAll('_',' '))}finally{setBusy(false)}};
 const reward=async()=>{try{const w=await api.reward();setWallet(w);setRewardDone(true);setError(w.claimed?'250 demo credits collected':'Daily reward already collected')}catch(e){setError(e.message)}};
 const logout=async()=>{await api.logout();setUser(null);setWallet(null);setFavorites([]);setRecents([]);setRounds([]);onUser?.(null,{favorites:[],recents:[]});setMode('login')};
  return <><div className="modal accountModal" role="dialog" aria-modal="true" aria-label="Account"><div className="accountCard"><button className="close" onClick={onClose} aria-label="Close"><X/></button>{mode==='profile'&&user?<><UserRound className="accountIcon"/><small>PLAYER PROFILE</small><h2>{user.displayName}</h2><p>{user.email}</p><ResponsibleCheckBanner/><div className="balance"><span>DEMO CREDITS</span><b>{wallet?.balance??'—'}</b></div><button className="join wide" disabled={rewardDone} onClick={reward}><Gift/>{rewardDone?' DAILY REWARD COLLECTED':' COLLECT DAILY 250'}</button>{error&&<p className="formMessage">{error}</p>}<div className="profileStats"><span><Heart/> {favorites.length}<small>Favorites</small></span><span><History/> {recents.length}<small>Recently played</small></span></div><section className="roundHistory"><h3>Round history</h3>{rounds.length?<div>{rounds.slice(0,8).map(r=><article key={r.roundId}><div className="roundSummary"><span>{r.gameId}</span><small>{r.status}</small><b>{r.win>0?`+${r.win}`:`−${r.bet}`} cr</b></div><FairnessProof round={r}/></article>)}</div>:<p>No rounds played yet.</p>}</section><div className="profileActions"><button className="textBtn" onClick={()=>setOnSettings(true)}><Settings/> Settings</button><button className="textBtn" onClick={()=>setOnResp(true)}><Shield/> Play responsibly</button><button className="textBtn" onClick={logout}><LogOut/> Sign out</button></div></>:<><small>{mode==='register'?t('auth.createEyebrow'):t('auth.welcomeEyebrow')}</small><h2>{mode==='register'?t('auth.createTitle'):t('auth.signinTitle')}</h2><form onSubmit={submit}>{mode==='register'&&<label>{t('auth.displayName')}<input required minLength="2" maxLength="40" value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label>}<label>{t('auth.email')}<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>{t('auth.password')}<input required minLength="10" type="password" autoComplete={mode==='register'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="formError">{error}</p>}<button className="join wide" disabled={busy}>{busy?t('auth.wait'):mode==='register'?t('auth.createBtn'):t('auth.signinBtn')}</button></form><OauthButtons/><button className="textBtn" onClick={()=>{setError('');setMode(mode==='register'?'login':'register')}}>{mode==='register'?t('auth.toSignin'):t('auth.toRegister')}</button><p className="legal">{t('auth.legal')}</p></>}</div></div>{onSettings&&<AccountSettings onClose={()=>setOnSettings(false)}/>}{onResp&&<ResponsiblePlay onClose={()=>setOnResp(false)}/>}</>;
}
