import{track}from'./analytics';
const API=import.meta.env.VITE_API_URL||'/api';
let active=sessionStorage.getItem('arcade_authenticated')==='1';
async function request(path,options={}){const r=await fetch(`${API}${path}`,{...options,credentials:'include',headers:{'Content-Type':'application/json',...options.headers}});if(r.status===204)return null;const body=await r.json().catch(()=>({error:'invalid_response'}));if(r.status===401){active=false;sessionStorage.removeItem('arcade_authenticated')}if(!r.ok)throw new Error(body.error||`request_${r.status}`);return body}
export const api={
 register:async data=>{try{const r=await request('/auth/register',{method:'POST',body:JSON.stringify(data)});active=true;sessionStorage.setItem('arcade_authenticated','1');track('auth',{action:'register',success:true});return r}catch(e){track('auth',{action:'register',success:false});throw e}},
 login:async data=>{try{const r=await request('/auth/login',{method:'POST',body:JSON.stringify(data)});active=true;sessionStorage.setItem('arcade_authenticated','1');track('auth',{action:'login',success:true});return r}catch(e){track('auth',{action:'login',success:false});throw e}},
 logout:async()=>{try{await request('/auth/logout',{method:'POST'});track('auth',{action:'logout',success:true})}finally{active=false;sessionStorage.removeItem('arcade_authenticated')}},
 profile:()=>request('/profile'),wallet:()=>request('/wallet'),balance:()=>request('/wallet/balance'),bonusSession:gameId=>request(`/wallet/bonus-session?gameId=${encodeURIComponent(gameId)}`),reward:async()=>{const r=await request('/wallet/daily-reward',{method:'POST'});track('daily',{claimed:r.claimed,reward:r.reward});return r},
 bet:async data=>{try{const r=await request('/wallet/bet',{method:'POST',body:JSON.stringify(data)});track('bet',{amount:data.amount,accepted:true},{gameId:data.gameId});return r}catch(e){track('bet',{amount:data.amount,accepted:false},{gameId:data.gameId});throw e}},round:roundId=>request(`/wallet/rounds/${encodeURIComponent(roundId)}`),settle:async data=>{const r=await request('/wallet/settle',{method:'POST',body:JSON.stringify(data)});track('settle',{win:r.win,multiplier:r.multiplier},{gameId:data.gameId});return r},bonusSpin:async data=>{const r=await request('/wallet/bonus-spin',{method:'POST',body:JSON.stringify(data)});track('settle',{win:r.win,multiplier:r.multiplier},{gameId:data.gameId});return r},history:()=>request('/history/rounds'),
 favorites:()=>request('/favorites'),addFavorite:async id=>{const r=await request(`/favorites/${encodeURIComponent(id)}`,{method:'PUT'});track('favorite',{action:'add'},{gameId:id});return r},removeFavorite:async id=>{const r=await request(`/favorites/${encodeURIComponent(id)}`,{method:'DELETE'});track('favorite',{action:'remove'},{gameId:id});return r},
 recents:()=>request('/recents'),played:id=>request(`/recents/${encodeURIComponent(id)}`,{method:'POST'}),socialActivity:()=>request('/social/activity'),leaderboard:period=>request(`/social/leaderboard?period=${encodeURIComponent(period)}`),hasSession:()=>active
};
