const studios = [
  "Nova Forge",
  "Pixel Harbor",
  "Golden Reel",
  "Orbit Labs",
  "Wild Mint",
  "Neon Fox",
];
const types = [
  "Slots",
  "Crash",
  "Jackpots",
  "Arcade",
  "Table",
  "Instant",
  "New",
];
const nouns = [
  "Fortune",
  "Dragon",
  "Vault",
  "Jungle",
  "Cosmos",
  "Pharaoh",
  "Candy",
  "Pirate",
  "Ember",
  "Tiger",
  "Moon",
  "Diamond",
  "Temple",
  "Rush",
  "Crown",
  "Safari",
  "Cash",
  "Mystic",
  "Wolf",
  "Galaxy",
];
const icons = [
  "💎",
  "🐉",
  "👑",
  "🌙",
  "🔥",
  "🍒",
  "⚡",
  "🪙",
  "🦁",
  "🚀",
  "🎯",
  "🏆",
];
const playable = {
  5: {
    title: "Nova Classic Slots",
    studio: "Open Arcade",
    category: "Slots",
    icon: "🎰",
    slug: "slots-classic",
    serverGame: true,
    license: "MIT",
  },
  6: {
    title: "Skyline Crash",
    studio: "Open Arcade",
    category: "Crash",
    icon: "📈",
    slug: "crash",
    serverGame: true,
    license: "Original",
  },
  7: {
    title: "Prism Plinko",
    studio: "Open Arcade",
    category: "Instant",
    icon: "🔻",
    slug: "plinko",
    serverGame: true,
    license: "Original",
  },
  8: {
    title: "European Roulette",
    studio: "Open Arcade",
    category: "Table",
    icon: "🎡",
    slug: "roulette",
    serverGame: true,
    license: "Original",
  },
  9: {
    title: "Keno Plus",
    studio: "Open Arcade",
    category: "Table",
    icon: "🔢",
    slug: "keno",
    serverGame: true,
    license: "Original",
  },
  0: {
    title: "Classic 2048",
    studio: "Gabriele Cirulli",
    category: "Arcade",
    icon: "🔢",
    url: "./games/2048/index.html",
    license: "MIT",
  },
  1: {
    title: "Canvas Tetris",
    studio: "Dionysis Zindros",
    category: "Arcade",
    icon: "🧱",
    url: "./games/tetris/index.html",
    license: "MIT",
  },
  2: {
    title: "Night Racer",
    studio: "Jake Gordon",
    category: "Arcade",
    icon: "🏎️",
    url: "./games/racer/index.html",
    license: "MIT",
  },
  3: {
    title: "Radius Raid",
    studio: "Jack Rugile",
    category: "Arcade",
    icon: "🚀",
    url: "./games/radius-raid/index.html",
    license: "MIT",
  },
  4: {
    title: "Classic Pong",
    studio: "Jake Gordon",
    category: "Arcade",
    icon: "🏓",
    url: "./games/pong/index.html",
    license: "MIT",
  },
};
const coreGames = Array.from({ length: 10 }, (_, i) => ({
  id: `game-${i + 1}`,
  title: `${nouns[i % nouns.length]} ${nouns[(i * 7 + 3) % nouns.length]}`,
  studio: studios[i % studios.length],
  category: types[i % types.length],
  icon: icons[i % icons.length],
  hot: i % 7 === 0,
  new: i % 11 === 0,
  rating: (4 + (i % 10) / 10).toFixed(1),
  hue: (i * 37) % 360,
  ...playable[i],
}));
export const games = [
  ...coreGames,
  ...littleJsGames.map((game, index) => ({
    ...game,
    hot: index % 13 === 0,
    new: index % 17 === 0,
    rating: (4 + (index % 10) / 10).toFixed(1),
    hue: ((index + 10) * 37) % 360,
  })),
  ...slotTitles,
];
export const categories = [
  "All",
  "Popular",
  "Favorites",
  "Recent",
  ...new Set(games.map((game) => game.category)),
];
import littleJsGames from "./littlejs.generated.json";
import slotTitles from "./slot-titles.generated.json";
