import React,{useEffect,useState}from"react";
import{ChevronRight,Clock,HelpCircle,ShieldCheck,X}from"lucide-react";
import"./trust-ux.css";

const ONBOARDING="arcade_onboarding_v1",START="arcade_session_started",REMINDER="arcade_session_reminder_minutes";
const steps=[
  {title:"Play for entertainment",copy:"Every balance is virtual. Credits cannot be bought, withdrawn, redeemed, or exchanged for prizes."},
  {title:"The server decides rounds",copy:"Wallet games debit and settle on the server. Open your round history to inspect each completed round."},
  {title:"Verify, then take a break",copy:"Recalculate a round commitment in your browser and choose a session reminder that suits you."},
];
export function Onboarding({onDone}){const[step,setStep]=useState(0),done=()=>{localStorage.setItem(ONBOARDING,"done");onDone()};return <div className="modal trustModal" role="dialog" aria-modal="true" aria-labelledby="onboarding-title"><div className="trustCard"><button className="close" onClick={done} aria-label="Skip introduction"><X/></button><small>WELCOME · {step+1} OF {steps.length}</small><h2 id="onboarding-title">{steps[step].title}</h2><p>{steps[step].copy}</p><div className="stepDots" aria-label={`Step ${step+1} of ${steps.length}`}>{steps.map((_,i)=><i key={i} className={i===step?"active":""}/>)}</div><button autoFocus className="join wide" onClick={()=>step===steps.length-1?done():setStep(x=>x+1)}>{step===steps.length-1?"START EXPLORING":"NEXT"}<ChevronRight/></button></div></div>}
export const needsOnboarding=()=>localStorage.getItem(ONBOARDING)!=="done";

export function HelpCenter({onClose}){const[minutes,setMinutes]=useState(()=>localStorage.getItem(REMINDER)||"30");const update=e=>{setMinutes(e.target.value);localStorage.setItem(REMINDER,e.target.value);sessionStorage.setItem(START,String(Date.now()))};return <div className="modal trustModal" role="dialog" aria-modal="true" aria-labelledby="help-title"><div className="trustCard helpCard"><button autoFocus className="close" onClick={onClose} aria-label="Close help"><X/></button><HelpCircle className="trustIcon"/><small>HELP CENTER</small><h2 id="help-title">Straight answers</h2><details open><summary>Do credits have monetary value?</summary><p>No. Credits are free entertainment counters. There are no deposits, purchases, withdrawals, cash prizes, or redemption.</p></details><details><summary>How do I verify a round?</summary><p>Sign in, open Profile → Round history, expand “Verify fairness,” then choose “Recalculate in browser.” The revealed seed must match the commitment made before play.</p></details><details><summary>How do daily and slot bonuses work?</summary><p>The daily collection adds 250 virtual credits once per UTC day. Eligible slot rounds may create server-persisted free-spin or respin sessions.</p></details><details><summary>What analytics are collected?</summary><p>Only after consent, the platform records allowlisted product events and a hashed anonymous session identifier. It does not store search text or session replay.</p></details><details><summary>Can support recover my password?</summary><p>Password recovery and operator support are not connected in this demo. Do not reuse an important password. A public operator must configure a verified support channel before launch.</p></details><label className="reminderSetting"><Clock/><span><b>Session reminder</b><small>Stored only in this browser</small></span><select value={minutes} onChange={update} aria-label="Session reminder interval"><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">60 minutes</option><option value="off">Off</option></select></label></div></div>}

export function SessionReminder(){const[visible,setVisible]=useState(false);useEffect(()=>{if(!sessionStorage.getItem(START))sessionStorage.setItem(START,String(Date.now()));if(!localStorage.getItem(REMINDER))localStorage.setItem(REMINDER,"30");const check=()=>{const setting=localStorage.getItem(REMINDER);if(setting==="off")return;const elapsed=Date.now()-Number(sessionStorage.getItem(START)||Date.now());if(elapsed>=Number(setting)*60_000)setVisible(true)};check();const timer=setInterval(check,30_000);return()=>clearInterval(timer)},[]);if(!visible)return null;const reset=()=>{sessionStorage.setItem(START,String(Date.now()));setVisible(false)};return <div className="modal trustModal" role="dialog" aria-modal="true" aria-labelledby="break-title"><div className="trustCard"><Clock className="trustIcon"/><small>SESSION REMINDER</small><h2 id="break-title">Time for a pause?</h2><p>You have reached your chosen reminder. Your virtual balance and account will remain here.</p><button autoFocus className="join wide" onClick={reset}>CONTINUE SESSION</button><button className="textBtn" onClick={()=>location.assign("about:blank")}>LEAVE FOR NOW</button></div></div>}
