import React,{useCallback,useEffect,useState}from'react';import{useDialog}from'./useDialog';
import{X,Gift,LogOut,UserRound,Heart,History}from'lucide-react';
import{api}from'./api';
import{track}from'./analytics';
import'./profile-stats.css';import'./personalization.css';
export default function AccountPanel({onClose,onUser}){
 const[mode,setMode]=useState(api.hasSession()?'profile':'register'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[displayName,setDisplayName]=useState(''),[user,setUser]=useState(null),[wallet,setWallet]=useState(null),[favorites,setFavorites]=useState([]),[recents,setRecents]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[rewardDone,setRewardDone]=useState(false);
 const load=useCallback(async()=>{try{const[p,w,f,r]=await Promise.all([api.profile(),api.wallet(),api.favorites(),api.recents()]);setUser(p.user);setWallet(w);setFavorites(f.games);setRecents(r.games);setRewardDone(w.ledger?.some(x=>x.idempotencyKey===`daily:${new Date().toISOString().slice(0,10)}`));onUser?.(p.user,{favorites:f.games,recents:r.games})}catch{setMode('login')}},[onUser]);
 useEffect(()=>{if(api.hasSession())load()},[load]);
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const r=mode==='register'?await api.register({email,password,displayName}):await api.login({email,password});setUser(r.user);setMode('profile');track(`${mode}_complete`);await load()}catch(err){setError(err.message.replaceAll('_',' '));track(`${mode}_failed`)}finally{setBusy(false)}};
 const reward=async()=>{try{const w=await api.reward();setWallet(w);setRewardDone(true);setError(w.claimed?'250 demo credits collected':'Daily reward already collected')}catch(e){setError(e.message)}};
 const logout=async()=>{await api.logout();setUser(null);setWallet(null);setFavorites([]);setRecents([]);onUser?.(null,{favorites:[],recents:[]});setMode('login')};
 const dialogRef=useDialog(onClose);
 return <div className="modal accountModal" role="dialog" aria-modal="true" aria-label="Account" ref={dialogRef} tabIndex={-1}><div className="accountCard"><button className="close" onClick={onClose} aria-label="Close"><X/></button>{mode==='profile'&&user?<><UserRound className="accountIcon"/><small>PLAYER PROFILE</small><h2>{user.displayName}</h2><p>{user.email}</p><div className="balance"><span>DEMO CREDITS</span><b>{wallet?.balance??'—'}</b></div><button className="join wide" disabled={rewardDone} onClick={reward}><Gift/>{rewardDone?' DAILY REWARD COLLECTED':' COLLECT DAILY 250'}</button>{error&&<p className="formMessage">{error}</p>}<div className="profileStats"><span><Heart/> {favorites.length}<small>Favorites</small></span><span><History/> {recents.length}<small>Recently played</small></span></div><button className="textBtn" onClick={logout}><LogOut/> Sign out</button></>:<><small>{mode==='register'?'CREATE PLAYER PROFILE':'WELCOME BACK'}</small><h2>{mode==='register'?'Join the club':'Sign in'}</h2><form onSubmit={submit}>{mode==='register'&&<label>Display name<input required minLength="2" maxLength="40" value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label>}<label>Email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required minLength="10" type="password" autoComplete={mode==='register'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="formError">{error}</p>}<button className="join wide" disabled={busy}>{busy?'PLEASE WAIT…':mode==='register'?'CREATE ACCOUNT':'SIGN IN'}</button></form><button className="textBtn" onClick={()=>{setError('');setMode(mode==='register'?'login':'register')}}>{mode==='register'?'Already a member? Sign in':'New here? Create account'}</button><p className="legal">18+ · Entertainment only · Credits have no cash value</p></>}</div></div>
}
