// ═══════════════════════════════════════════════════════════
// GAME CATALOG — single source of truth for every playable title
//
// Design rules (project-wide):
//  * No hardcoded strings in consumers — everything resolvable from here.
//  * `GAMES` is the rich record. The lobby UI shape (`games`) is *derived*,
//    so adding a game never means touching two lists.
//  * Studio attribution is honest: every title is an in-house casino game
//    carrying one of our own studio brands.
// ═══════════════════════════════════════════════════════════

// ─── Studios ────────────────────────────────────────────────
// In-house brands only — the portfolio is casino titles exclusively
// (slots, table, live, instant). Licensing is in docs/GAME_LICENSES.md.
const STUDIOS = Object.freeze({
  nova: { id: 'nova', name: 'Nova Reels', inHouse: true },
  vertex: { id: 'vertex', name: 'Vertex Live', inHouse: true },
  pulse: { id: 'pulse', name: 'Pulse Instant', inHouse: true },
});

// ─── Categories ─────────────────────────────────────────────
// `label` is what the lobby filter chips render and what a game's derived
// `category` field matches against.
const CATEGORIES = Object.freeze([
  { id: 'slots', label: 'Slots', hue: 275 },
  { id: 'table-games', label: 'Table', hue: 150 },
  { id: 'live-casino', label: 'Live', hue: 8 },
  { id: 'instant', label: 'Instant', hue: 42 },
]);

// Virtual filters the lobby prepends — they are computed, not stored per game.
const VIRTUAL_CATEGORIES = Object.freeze(['All', 'Popular', 'Favorites', 'Recent']);

const CATEGORY_BY_ID = Object.freeze(
  Object.fromEntries(CATEGORIES.map((c) => [c.id, c])),
);

// ─── Licensing ──────────────────────────────────────────────
const LICENSES = Object.freeze({
  inHouse: 'Proprietary',
  mit: 'MIT',
});

// ─── Volatility scale ───────────────────────────────────────
// Ordered scale so the UI can sort/badge without magic strings.
const VOLATILITY = Object.freeze(['low', 'medium', 'high', 'very-high', 'variable']);

/**
 * Titles with generated cover art (`npm run build:covers`).
 *
 * Every game has one, drawn from the same procedural art system the
 * games themselves use.
 *
 * The list is asserted against the filesystem in both directions by the
 * catalog tests, so it cannot drift from what the build actually produced.
 */
const COVERED = new Set([
  // Engine-driven slots — cover derived from the game's own symbol cast.
  'cosmic-queen', 'dragons-fortune', 'pharaohs-treasure', 'slots-royal',
  'book-of-gold', 'gold-caravan', 'magic-crystal', 'hot-navigator',
  'diamond-rush', 'wild-west-gold', 'lucky-streak', 'super-line-fruit-bomb',
  // Table, instant and dice titles — cover declared in game-math/cover-specs.js.
  'blackjack-pro', 'baccarat-pro', 'roulette-royale',
  'crash-pro', 'plinko-master', 'fruit-shop', 'lightning-dice',
  // Live casino games — gradient covers generated per provider palette.
  // Evolution Gaming
  'lightning-blackjack', 'mega-roulette', 'speed-baccarat', 'crazy-time',
  'monopoly-live', 'dream-catcher', 'lightning-roulette', 'infinite-blackjack',
  'auto-roulette', 'casino-holdem', 'three-card-poker', 'power-blackjack',
  // Pragmatic Play Live
  'pragmatic-lightning-baccarat', 'pragmatic-speed-roulette', 'pragmatic-auto-roulette',
  'pragmatic-blackjack-vip', 'pragmatic-standard-blackjack', 'pragmatic-super-sic-bo',
  'pragmatic-lucky-6-baccarat', 'pragmatic-dragon-tiger-pro', 'pragmatic-cash-or-crash',
  'pragmatic-wheel-fortune',
  // Ezugi
  'ezugi-lightning-sic-bo', 'ezugi-speed-baccarat', 'ezugi-asian-blackjack',
  'ezugi-auto-roulette', 'ezugi-super-and-bachet', 'ezugi-casino-stud-poker',
  'ezugi-no-commission-baccarat', 'ezugi-fast-play-roulette',
  // Vivo Gaming
  'vivo-blackjack', 'vivo-roulette', 'vivo-baccarat', 'vivo-casino-poker', 'vivo-sic-bo',
  // Endorphina live games (each has its own game directory and cover)
  'endorphina-live-poker', 'endorphina-lightning-dice', 'endorphina-speed-roulette',
  'endorphina-baccarat-gold', 'endorphina-blackjack-vip',
  // Catch-all / platform entries
  'pragmatic-live', 'betby-sports',
]);

// ─── Derivation defaults ────────────────────────────────────
const DERIVE = Object.freeze({
  gameBasePath: '/games',
  coverPath: (id) => (COVERED.has(id) ? `/games/${id}/cover.png` : null),
  // Ratings are editorial, 1 decimal. Absent → derived from the RTP so a new
  // entry never renders an empty star field.
  ratingFromRtp: (rtp) =>
    Math.min(5, Math.round((3.4 + (parseFloat(rtp) - 95) * 0.42) * 10) / 10),
  defaultRating: 4.5,
});

// ═══════════════════════════════════════════════════════════
// GAMES
// ═══════════════════════════════════════════════════════════

const GAMES = [
  // ── Slots ────────────────────────────────────────────────
  {
    id: 'slots-royal',
    name: 'Slots Royal',
    category: 'slots',
    studio: 'nova',
    glyph: '👑',
    rtp: '96.0%',
    volatility: 'high',
    minBet: 0.1,
    maxBet: 5000,
    reels: 5,
    rows: 3,
    paylines: 20,
    features: ['Wild Substitution', 'Free Spins', 'Progressive Jackpot'],
    tags: ['slots', 'classic', 'jackpot', 'fruit'],
    description:
      'Classic five-reel slot with a royal crest paytable, wild substitution and a four-tier progressive jackpot that seeds from every spin.',
    featured: true,
    popular: true,
    new: false,
  },
  {
    id: 'cosmic-queen',
    name: 'Cosmic Queen',
    category: 'slots',
    studio: 'nova',
    glyph: '🌌',
    rtp: '96.2%',
    volatility: 'very-high',
    minBet: 0.1,
    maxBet: 5000,
    reels: 5,
    rows: 3,
    paylines: 15,
    features: ['Expanding Wild', 'Free Spins', 'Cosmic Meter'],
    tags: ['slots', 'space', 'wild', 'meter'],
    description:
      'A deep-space five-reel with an expanding Cosmic Wild, a session meter that banks toward guaranteed free spins, and a high-variance top-end.',
    featured: true,
    popular: true,
    new: false,
  },
  {
    id: 'dragons-fortune',
    name: "Dragon's Fortune",
    category: 'slots',
    studio: 'nova',
    glyph: '🐉',
    rtp: '96.1%',
    volatility: 'high',
    minBet: 0.1,
    maxBet: 5000,
    reels: 5,
    rows: 3,
    paylines: 20,
    features: ['Fortune Meter', 'Free Spins', 'Multiplier Trail'],
    tags: ['slots', 'asian', 'dragon', 'multiplier'],
    description:
      'Asian-themed five-reel built around a ten-step Fortune Meter — every scatter advances it, and the top step pays a banked multiplier trail.',
    featured: false,
    popular: true,
    new: false,
  },
  {
    id: 'pharaohs-treasure',
    name: "Pharaoh's Treasure",
    category: 'slots',
    studio: 'nova',
    glyph: '🏺',
    rtp: '96.0%',
    volatility: 'high',
    minBet: 0.1,
    maxBet: 5000,
    reels: 5,
    rows: 3,
    paylines: 20,
    features: ['Expanding Symbol', 'Free Spins', 'Gamble'],
    tags: ['slots', 'egypt', 'expanding', 'gamble'],
    description:
      'Tomb-raiding five-reel where a single expanding symbol is drawn before the free-spin round and then pays across every position it lands on.',
    featured: false,
    popular: false,
    new: false,
  },
  {
    id: 'fruit-shop',
    name: 'Fruit Market',
    category: 'slots',
    studio: 'nova',
    glyph: '🍒',
    rtp: '96.0%',
    volatility: 'medium',
    minBet: 0.1,
    maxBet: 5000,
    reels: 5,
    rows: 3,
    paylines: 10,
    features: ['Sticky Wild', 'Free Spins', 'Gamble'],
    tags: ['slots', 'fruit', 'wild', 'gamble'],
    description:
      'Bright market-stall five-reel. Wilds on the middle reels turn sticky for the whole free-spin round, and every win can be gambled on card colour or suit.',
    featured: true,
    popular: true,
    new: false,
  },
  {
    id: 'gold-caravan',
    name: 'Gold Caravan',
    category: 'slots',
    studio: 'nova',
    glyph: '🐫',
    rtp: '96.0%',
    volatility: 'high',
    minBet: 0.1,
    maxBet: 5000,
    reels: 5,
    rows: 3,
    paylines: 10,
    features: ['Expanding Wild', 'Pick & Win Bonus', 'Free Spins'],
    tags: ['slots', 'desert', 'bonus', 'pick'],
    description:
      'Desert-route five-reel with a nine-crate Pick & Win bonus on reels 1-3-5 and caravan wilds that expand to fill their reel during free spins.',
    featured: false,
    popular: false,
    new: false,
  },
  {
    id: 'magic-crystal',
    name: 'Magic Crystal',
    category: 'slots',
    studio: 'nova',
    glyph: '🔮',
    rtp: '96.0%',
    volatility: 'medium',
    minBet: 0.1,
    maxBet: 5000,
    reels: 5,
    rows: 3,
    paylines: 10,
    features: ['Random Multiplier', 'Wheel Bonus', 'Free Spins'],
    tags: ['slots', 'fantasy', 'wheel', 'multiplier'],
    description:
      'Arcane five-reel where each free spin rolls a random 2×–10× multiplier, and three crystals open a weighted bonus wheel.',
    featured: false,
    popular: false,
    new: false,
  },
  {
    id: 'hot-navigator',
    name: 'Hot Navigator',
    category: 'slots',
    studio: 'nova',
    glyph: '🧭',
    rtp: '96.0%',
    volatility: 'high',
    minBet: 0.1,
    maxBet: 5000,
    reels: 5,
    rows: 3,
    paylines: 20,
    features: ['Expanding Wild', 'Direction Bonus', 'Free Spins'],
    tags: ['slots', 'nautical', 'bonus', 'wild'],
    description:
      'Seafaring five-reel with a compass bonus: pick a heading and the reels reveal the route, each leg adding to a banked multiplier.',
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'diamond-rush',
    name: 'Diamond Rush',
    category: 'slots',
    studio: 'nova',
    glyph: '💎',
    rtp: '96.0%',
    volatility: 'high',
    minBet: 0.1,
    maxBet: 5000,
    reels: 5,
    rows: 3,
    paylines: 20,
    features: ['Cascading Reels', 'Free Spins', 'Multiplier Ladder'],
    tags: ['slots', 'gems', 'cascade', 'multiplier'],
    description:
      'Cascading gem slot — every winning cluster clears and refills, stepping a multiplier ladder that resets only when a cascade ends dry.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'wild-west-gold',
    name: 'Wild West Gold',
    category: 'slots',
    studio: 'nova',
    glyph: '🤠',
    rtp: '96.2%',
    volatility: 'high',
    minBet: 0.1,
    maxBet: 5000,
    reels: 5,
    rows: 3,
    paylines: 20,
    features: ['Sticky Wild', 'Free Spins', 'Multiplier Wild'],
    tags: ['slots', 'western', 'wild', 'sticky'],
    description:
      'Frontier five-reel where wilds carry a 2×–5× stamp and lock in place for the remainder of the free-spin round.',
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'book-of-gold',
    name: 'Book of Gold',
    category: 'slots',
    studio: 'nova',
    glyph: '📖',
    rtp: '96.0%',
    volatility: 'very-high',
    minBet: 0.1,
    maxBet: 5000,
    reels: 5,
    rows: 3,
    paylines: 10,
    features: ['Expanding Symbol', 'Free Spins', 'Retrigger'],
    tags: ['slots', 'book', 'expanding', 'retrigger'],
    description:
      'Book-mechanic five-reel: one symbol is drawn at the start of the bonus, expands across full reels, and pays regardless of adjacency.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'super-line-fruit-bomb',
    name: 'Super Line: Fruit Bomb',
    category: 'slots',
    studio: 'nova',
    glyph: '💣',
    rtp: '96.0%',
    volatility: 'high',
    minBet: 0.1,
    maxBet: 5000,
    reels: 5,
    rows: 3,
    paylines: 20,
    features: ['Bomb Wild', 'Free Spins', 'Wild Substitution'],
    tags: ['slots', 'fruit', 'bomb', 'wild'],
    description:
      'Twenty-line fruit slot with a Bomb Wild that detonates on landing, converting neighbouring positions to wild before payouts resolve.',
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'lucky-streak',
    name: 'Lucky Streak',
    category: 'slots',
    studio: 'nova',
    glyph: '🍀',
    rtp: '96.0%',
    volatility: 'high',
    minBet: 0.1,
    maxBet: 5000,
    reels: 5,
    rows: 3,
    paylines: 15,
    features: ['Streak Meter', 'Free Spins', 'Wild Substitution'],
    tags: ['slots', 'clover', 'streak', 'meter'],
    description:
      'Consecutive wins feed a streak meter; hold the streak and the meter converts to free spins with an escalating base multiplier.',
    featured: false,
    popular: false,
    new: true,
  },

  // ── Table ────────────────────────────────────────────────
  {
    id: 'blackjack-pro',
    name: 'Blackjack Pro',
    category: 'table-games',
    studio: 'vertex',
    glyph: '🃏',
    rtp: '99.5%',
    volatility: 'low',
    minBet: 0.5,
    maxBet: 20000,
    features: ['Side Bets', 'Double Down', 'Insurance', 'Multi-hand'],
    tags: ['blackjack', 'cards', 'table', 'strategy'],
    description:
      'Six-deck blackjack, dealer stands on all 17, naturals pay 3:2. Includes Perfect Pairs and 21+3 side bets and a running-count display.',
    featured: true,
    popular: true,
    new: false,
  },
  {
    id: 'baccarat-pro',
    name: 'Baccarat Pro',
    category: 'table-games',
    studio: 'vertex',
    glyph: '🎴',
    rtp: '98.9%',
    volatility: 'medium',
    minBet: 0.5,
    maxBet: 20000,
    features: ['Player / Banker / Tie', 'Third-card Rule', 'Roadmaps'],
    tags: ['baccarat', 'cards', 'table', 'punto'],
    description:
      'Eight-deck baccarat with the full third-card rule, 5% banker commission and bead-plate / big-road tracking.',
    featured: false,
    popular: true,
    new: false,
  },
  {
    id: 'roulette-royale',
    name: 'Roulette Royale',
    category: 'table-games',
    studio: 'vertex',
    glyph: '🎡',
    rtp: '97.3%',
    volatility: 'medium',
    minBet: 0.1,
    maxBet: 25000,
    features: ['European Wheel', 'Hot & Cold', 'Racetrack Bets'],
    tags: ['roulette', 'wheel', 'table', 'european'],
    description:
      'Single-zero European roulette with the full inside/outside bet set, racetrack call bets and rolling hot/cold number statistics.',
    featured: true,
    popular: true,
    new: false,
  },

  // ── Live Casino — Evolution Gaming ───────────────────────
  {
    id: 'lightning-blackjack',
    name: 'Lightning Blackjack',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '⚡',
    rtp: '98.5%',
    volatility: 'low',
    minBet: 10,
    maxBet: 10000,
    features: ['Lightning Multipliers 2x-100x', 'Side Bets', 'Live Dealer'],
    tags: ['blackjack', 'live', 'lightning', 'evolution'],
    description:
      'Evolution Lightning Blackjack — standard rules with random multipliers up to 100× on winning hands.',
    featured: true,
    popular: true,
    new: true,
  },
  {
    id: 'mega-roulette',
    name: 'Mega Roulette',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🎡',
    rtp: '97.3%',
    volatility: 'medium',
    minBet: 0.5,
    maxBet: 25000,
    features: ['Progressive Jackpot', 'Live Dealer', 'Full Bet Set'],
    tags: ['roulette', 'live', 'mega', 'evolution', 'jackpot'],
    description:
      'Evolution Mega Roulette — European wheel with progressive jackpot on straight bets and live dealer experience.',
    featured: true,
    popular: true,
    new: true,
  },
  {
    id: 'speed-baccarat',
    name: 'Speed Baccarat',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '⏱️',
    rtp: '98.9%',
    volatility: 'medium',
    minBet: 5,
    maxBet: 15000,
    features: ['Rapid Play 15s', 'No Commission', 'Live Dealer'],
    tags: ['baccarat', 'live', 'speed', 'evolution'],
    description:
      'Evolution Speed Baccarat — rapid 15-second rounds with no commission on Banker wins.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'crazy-time',
    name: 'Crazy Time',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🤡',
    rtp: '95.5%',
    volatility: 'very-high',
    minBet: 1,
    maxBet: 5000,
    features: ['4 Bonus Rounds', 'Coin Flip', 'Cash Hunt', 'Pachinko', 'Crazy Time'],
    tags: ['game-show', 'live', 'crazy-time', 'evolution', 'bonus'],
    description:
      'Evolution Crazy Time — iconic game show with four bonus rounds, top-slot multipliers up to 100×, and massive payouts.',
    featured: true,
    popular: true,
    new: true,
  },
  {
    id: 'monopoly-live',
    name: 'Monopoly Live',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🎩',
    rtp: '96.2%',
    volatility: 'high',
    minBet: 1,
    maxBet: 5000,
    features: ['3D Board Bonus', 'Double Wheel', 'Live Dealer'],
    tags: ['game-show', 'live', 'monopoly', 'evolution', 'board-game'],
    description:
      'Evolution Monopoly Live — wheel-based game show with a 3D Monopoly board bonus round and free spins.',
    featured: true,
    popular: true,
    new: true,
  },
  {
    id: 'dream-catcher',
    name: 'Dream Catcher',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🌈',
    rtp: '96.08%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 5000,
    features: ['Money Wheel', 'Double Segments', 'Live Dealer'],
    tags: ['wheel', 'live', 'dream-catcher', 'evolution'],
    description:
      'Evolution Dream Catcher — large money wheel with segments 1/2/5/10/20/40/70 and double flappers for bonus rounds.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'lightning-roulette',
    name: 'Lightning Roulette',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '⚡',
    rtp: '97.3%',
    volatility: 'very-high',
    minBet: 0.5,
    maxBet: 10000,
    features: ['Lightning Multipliers 50x-500x', 'Live Dealer', 'Progressive'],
    tags: ['roulette', 'live', 'lightning', 'evolution', 'multiplier'],
    description:
      'Evolution Lightning Roulette — 1-5 numbers struck by lightning per spin with multipliers from 50× to 500×.',
    featured: true,
    popular: true,
    new: true,
  },
  {
    id: 'infinite-blackjack',
    name: 'Infinite Blackjack',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '♾️',
    rtp: '99.6%',
    volatility: 'low',
    minBet: 0.5,
    maxBet: 5000,
    features: ['Unlimited Seats', 'Side Bets', 'Live Dealer'],
    tags: ['blackjack', 'live', 'infinite', 'evolution'],
    description:
      'Evolution Infinite Blackjack — unlimited player seats, standard rules, dealer stands on 17.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'auto-roulette',
    name: 'Auto Roulette',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🤖',
    rtp: '97.3%',
    volatility: 'medium',
    minBet: 0.1,
    maxBet: 5000,
    features: ['Automated', 'No Dealer', 'Fast Spin'],
    tags: ['roulette', 'live', 'auto', 'evolution'],
    description:
      'Evolution Auto Roulette — fully automated European roulette with rapid spins and no live dealer.',
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'casino-holdem',
    name: "Casino Hold'em",
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🃏',
    rtp: '97.8%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 5000,
    features: ['Ace-Five Bonus', 'Community Cards', 'Live Dealer'],
    tags: ['poker', 'live', 'holdem', 'evolution'],
    description:
      "Evolution Casino Hold'em — players compete against the dealer's hand with Ace-Five bonus side bet.",
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'three-card-poker',
    name: 'Three Card Poker',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🎴',
    rtp: '96.43%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 5000,
    features: ['Ante/Play', 'Pair Plus', 'Live Dealer'],
    tags: ['poker', 'live', 'three-card', 'evolution'],
    description:
      'Evolution Three Card Poker — ante/play with Pair Plus side bet, dealer qualifies with Queen or better.',
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'power-blackjack',
    name: 'Power Blackjack',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '💪',
    rtp: '99.28%',
    volatility: 'low',
    minBet: 10,
    maxBet: 10000,
    features: ['Double on Any Cards', 'Split Once', 'Live Dealer'],
    tags: ['blackjack', 'live', 'power', 'evolution'],
    description:
      'Evolution Power Blackjack — double on any two cards (not just first two), split once to two hands.',
    featured: false,
    popular: false,
    new: true,
  },

  // ── Live Casino — Pragmatic Play Live ────────────────────
  {
    id: 'pragmatic-lightning-baccarat',
    name: 'Pragmatic Lightning Baccarat',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '⚡',
    rtp: '98.94%',
    volatility: 'medium',
    minBet: 5,
    maxBet: 10000,
    features: ['Lightning Multipliers 2x-100x', 'Live Dealer'],
    tags: ['baccarat', 'live', 'lightning', 'pragmatic'],
    description:
      'Pragmatic Play Lightning Baccarat — random multipliers on Player/Banker/Tie bets up to 100×.',
    featured: true,
    popular: true,
    new: true,
  },
  {
    id: 'pragmatic-speed-roulette',
    name: 'Pragmatic Speed Roulette',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '⏱️',
    rtp: '97.3%',
    volatility: 'medium',
    minBet: 0.5,
    maxBet: 10000,
    features: ['25s Spin Time', 'Rapid Play', 'Live Dealer'],
    tags: ['roulette', 'live', 'speed', 'pragmatic'],
    description:
      'Pragmatic Speed Roulette — 25-second spin time for rapid European roulette action.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'pragmatic-auto-roulette',
    name: 'Pragmatic Auto Roulette',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🤖',
    rtp: '97.3%',
    volatility: 'medium',
    minBet: 0.1,
    maxBet: 5000,
    features: ['Automated', 'European Wheel', 'Fast Play'],
    tags: ['roulette', 'live', 'auto', 'pragmatic'],
    description:
      'Pragmatic Auto Roulette — automated European roulette with rapid continuous play.',
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'pragmatic-blackjack-vip',
    name: 'Pragmatic Blackjack VIP',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '👑',
    rtp: '99.5%',
    volatility: 'low',
    minBet: 50,
    maxBet: 25000,
    features: ['VIP Table', 'High Limits', 'Side Bets'],
    tags: ['blackjack', 'live', 'vip', 'pragmatic'],
    description:
      'Pragmatic Blackjack VIP — exclusive high-limit table with premium dealer experience.',
    featured: true,
    popular: false,
    new: true,
  },
  {
    id: 'pragmatic-standard-blackjack',
    name: 'Pragmatic Standard Blackjack',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🃏',
    rtp: '99.5%',
    volatility: 'low',
    minBet: 0.5,
    maxBet: 5000,
    features: ['Standard Rules', 'Side Bets', 'Live Dealer'],
    tags: ['blackjack', 'live', 'standard', 'pragmatic'],
    description:
      'Pragmatic Standard Blackjack — six-deck, dealer stands on 17, full side bet set.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'pragmatic-super-sic-bo',
    name: 'Pragmatic Super Sic Bo',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🎲',
    rtp: '97.2%',
    volatility: 'high',
    minBet: 0.1,
    maxBet: 5000,
    features: ['Lightning Multipliers', 'Triple Bonus', 'Live Dealer'],
    tags: ['sic-bo', 'live', 'dice', 'pragmatic'],
    description:
      'Pragmatic Super Sic Bo — three dice with lightning multipliers up to 100× on selected combinations.',
    featured: true,
    popular: true,
    new: true,
  },
  {
    id: 'pragmatic-lucky-6-baccarat',
    name: 'Pragmatic Lucky 6 Baccarat',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🍀',
    rtp: '97.5%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 5000,
    features: ['Lucky 6 Side Bet', 'Dragon Bonus', 'Live Dealer'],
    tags: ['baccarat', 'live', 'lucky-6', 'pragmatic'],
    description:
      'Pragmatic Lucky 6 Baccarat — side bet on Banker winning with exactly six cards, Dragon Bonus included.',
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'pragmatic-dragon-tiger-pro',
    name: 'Pragmatic Dragon Tiger Pro',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🐉',
    rtp: '96.81%',
    volatility: 'medium',
    minBet: 0.5,
    maxBet: 5000,
    features: ['Side Bets', 'Ora Side Bet', 'Live Dealer'],
    tags: ['dragon-tiger', 'live', 'cards', 'pragmatic'],
    description:
      'Pragmatic Dragon Tiger Pro — simple two-card game with multiple side bets and rapid rounds.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'pragmatic-cash-or-crash',
    name: 'Pragmatic Cash or Crash Live',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '💰',
    rtp: '95.8%',
    volatility: 'very-high',
    minBet: 1,
    maxBet: 5000,
    features: ['Risk/Reward Bonus', 'Multiplier Ladder', 'Live Dealer'],
    tags: ['game-show', 'live', 'cash-or-crash', 'pragmatic'],
    description:
      'Pragmatic Cash or Crash Live — risk/reward bonus round with escalating multipliers and crash mechanic.',
    featured: true,
    popular: true,
    new: true,
  },
  {
    id: 'pragmatic-wheel-fortune',
    name: 'Pragmatic Wheel of Fortune Live',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🎡',
    rtp: '96.0%',
    volatility: 'high',
    minBet: 1,
    maxBet: 5000,
    features: ['Money Wheel', 'Bonus Rounds', 'Live Dealer'],
    tags: ['wheel', 'live', 'fortune', 'pragmatic'],
    description:
      'Pragmatic Wheel of Fortune Live — classic money wheel with bonus rounds and multipliers.',
    featured: false,
    popular: false,
    new: true,
  },

  // ── Live Casino — Ezugi ──────────────────────────────────
  {
    id: 'ezugi-lightning-sic-bo',
    name: 'Ezugi Lightning Sic Bo',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '⚡',
    rtp: '97.2%',
    volatility: 'high',
    minBet: 0.1,
    maxBet: 5000,
    features: ['Lightning Multipliers', 'Triple Bonus', 'Live Dealer'],
    tags: ['sic-bo', 'live', 'lightning', 'ezugi'],
    description:
      'Ezugi Lightning Sic Bo — three dice with lightning strikes boosting selected totals up to 100×.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'ezugi-speed-baccarat',
    name: 'Ezugi Speed Baccarat',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '⏱️',
    rtp: '98.9%',
    volatility: 'medium',
    minBet: 5,
    maxBet: 10000,
    features: ['Rapid Play', 'No Commission', 'Live Dealer'],
    tags: ['baccarat', 'live', 'speed', 'ezugi'],
    description:
      'Ezugi Speed Baccarat — rapid baccarat rounds with no commission on Banker wins.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'ezugi-asian-blackjack',
    name: 'Ezugi Asian Blackjack',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🀄',
    rtp: '98.5%',
    volatility: 'low',
    minBet: 0.5,
    maxBet: 3000,
    features: ['Asian Rules', 'Double After Split', 'Live Dealer'],
    tags: ['blackjack', 'live', 'asian', 'ezugi'],
    description:
      'Ezugi Asian Blackjack — Asian-style rules with double after split and lower house edge.',
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'ezugi-auto-roulette',
    name: 'Ezugi Auto Roulette',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🤖',
    rtp: '97.3%',
    volatility: 'medium',
    minBet: 0.1,
    maxBet: 5000,
    features: ['Automated', 'European Wheel', 'Fast Play'],
    tags: ['roulette', 'live', 'auto', 'ezugi'],
    description:
      'Ezugi Auto Roulette — automated European roulette with rapid continuous play.',
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'ezugi-super-and-bachet',
    name: 'Ezugi Super And Bachet',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🎴',
    rtp: '96.0%',
    volatility: 'high',
    minBet: 1,
    maxBet: 5000,
    features: ['Asian Card Game', 'Side Bets', 'Live Dealer'],
    tags: ['and-bachet', 'live', 'asian', 'ezugi'],
    description:
      'Ezugi Super And Bachet — popular Asian card game with side bets and live dealer.',
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'ezugi-casino-stud-poker',
    name: 'Ezugi Casino Stud Poker',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🃏',
    rtp: '96.62%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 5000,
    features: ['Five Card Stud', 'Ante Bonus', 'Live Dealer'],
    tags: ['poker', 'live', 'stud', 'ezugi'],
    description:
      'Ezugi Casino Stud Poker — five-card stud with ante bonus and progressive jackpot option.',
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'ezugi-no-commission-baccarat',
    name: 'Ezugi No Commission Baccarat',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🎴',
    rtp: '98.94%',
    volatility: 'medium',
    minBet: 0.5,
    maxBet: 10000,
    features: ['No Commission', 'Dragon Bonus', 'Live Dealer'],
    tags: ['baccarat', 'live', 'no-commission', 'ezugi'],
    description:
      'Ezugi No Commission Baccarat — no 5% commission on Banker wins with Dragon Bonus side bet.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'ezugi-fast-play-roulette',
    name: 'Ezugi Fast Play Roulette',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '⚡',
    rtp: '97.3%',
    volatility: 'medium',
    minBet: 0.1,
    maxBet: 5000,
    features: ['Fast Spin', 'European Wheel', 'Live Dealer'],
    tags: ['roulette', 'live', 'fast', 'ezugi'],
    description:
      'Ezugi Fast Play Roulette — rapid European roulette with quick bet resolution.',
    featured: false,
    popular: false,
    new: true,
  },

  // ── Live Casino — Vivo Gaming ────────────────────────────
  {
    id: 'vivo-blackjack',
    name: 'Vivo Live Blackjack',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🃏',
    rtp: '99.5%',
    volatility: 'low',
    minBet: 0.5,
    maxBet: 5000,
    features: ['Standard Rules', 'Side Bets', 'Live Dealer'],
    tags: ['blackjack', 'live', 'vivo'],
    description:
      'Vivo Gaming Live Blackjack — standard six-deck blackjack with dealer stands on 17.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'vivo-roulette',
    name: 'Vivo Live Roulette',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🎡',
    rtp: '97.3%',
    volatility: 'medium',
    minBet: 0.1,
    maxBet: 5000,
    features: ['European Wheel', 'Full Bet Set', 'Live Dealer'],
    tags: ['roulette', 'live', 'vivo'],
    description:
      'Vivo Gaming Live Roulette — European single-zero wheel with complete inside/outside bet set.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'vivo-baccarat',
    name: 'Vivo Live Baccarat',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🎴',
    rtp: '98.9%',
    volatility: 'medium',
    minBet: 0.5,
    maxBet: 10000,
    features: ['Eight-Deck Shoe', '5% Commission', 'Live Dealer'],
    tags: ['baccarat', 'live', 'vivo'],
    description:
      'Vivo Gaming Live Baccarat — classic eight-deck baccarat with 5% Banker commission.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'vivo-casino-poker',
    name: 'Vivo Casino Poker',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🃏',
    rtp: '96.5%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 5000,
    features: ['Texas Hold\'em Style', 'Community Cards', 'Live Dealer'],
    tags: ['poker', 'live', 'vivo'],
    description:
      'Vivo Gaming Casino Poker — Texas Hold\'em style poker against the house with community cards.',
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'vivo-sic-bo',
    name: 'Vivo Sic Bo Live',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🎲',
    rtp: '97.2%',
    volatility: 'high',
    minBet: 0.1,
    maxBet: 5000,
    features: ['Three Dice', 'Big/Small Bets', 'Live Dealer'],
    tags: ['sic-bo', 'live', 'dice', 'vivo'],
    description:
      'Vivo Gaming Sic Bo Live — three dice game with Big/Small and specific combination bets.',
    featured: false,
    popular: false,
    new: true,
  },

  // ── Sports Betting — BetBy Sports ─────────────────────────
  {
    id: 'betby-sports',
    name: 'BetBy Sports',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '⚽',
    rtp: '97.0%',
    volatility: 'variable',
    minBet: 0.5,
    maxBet: 25000,
    features: ['Pre-Match Odds', 'Live Betting', 'Multiple Sports', 'Bet Slip'],
    tags: ['sports', 'betting', 'football', 'basketball', 'tennis', 'hockey'],
    description:
      'BetBy Sports — full sports betting platform with pre-match and live odds for football, basketball, tennis, hockey and more. Includes bet slip, history and multi-sport support.',
    featured: true,
    popular: true,
    new: true,
  },

  // ── Live Casino — Pragmatic Play Live ────────────────────
  {
    id: 'pragmatic-live',
    name: 'Pragmatic Play Live',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🎰',
    rtp: '96.5%',
    volatility: 'variable',
    minBet: 0.2,
    maxBet: 25000,
    features: ['Live Dealer', 'Blackjack', 'Roulette', 'Baccarat', 'Game Shows'],
    tags: ['pragmatic', 'live', 'dealer', 'blackjack', 'roulette', 'baccarat', 'game-show'],
    description:
      'Pragmatic Play Live — premium live dealer games including Lightning Roulette, Blackjack B, VIP Baccarat, Crazy Time and more with professional dealers.',
    featured: true,
    popular: true,
    new: true,
  },

  // ── Live Casino — Endorphina ─────────────────────────────
  {
    id: 'endorphina-live-poker',
    name: 'Endorphina Live Poker',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🃏',
    rtp: '97.3%',
    volatility: 'medium',
    minBet: 0.5,
    maxBet: 5000,
    features: ['Video Poker Style', 'Multi-Hand', 'Live Dealer'],
    tags: ['poker', 'live', 'endorphina'],
    description:
      'Endorphina Live Poker — multi-hand video poker style game with live dealer interaction.',
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'endorphina-lightning-dice',
    name: 'Endorphina Lightning Dice',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '⚡',
    rtp: '96.2%',
    volatility: 'very-high',
    minBet: 0.1,
    maxBet: 10000,
    features: ['Lightning Multipliers', 'Three Dice', 'Live Dealer'],
    tags: ['dice', 'live', 'lightning', 'endorphina'],
    description:
      'Endorphina Lightning Dice — three dice totals with lightning strikes boosting selected numbers up to 100×.',
    featured: true,
    popular: true,
    new: true,
  },
  {
    id: 'endorphina-speed-roulette',
    name: 'Endorphina Speed Roulette',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '⏱️',
    rtp: '97.3%',
    volatility: 'medium',
    minBet: 0.1,
    maxBet: 5000,
    features: ['Rapid Spin', 'European Wheel', 'Live Dealer'],
    tags: ['roulette', 'live', 'speed', 'endorphina'],
    description:
      'Endorphina Speed Roulette — rapid European roulette with quick bet placement and resolution.',
    featured: false,
    popular: false,
    new: true,
  },
  {
    id: 'endorphina-baccarat-gold',
    name: 'Endorphina Baccarat Gold',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🏆',
    rtp: '98.9%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 10000,
    features: ['Gold Card Effects', 'No Commission', 'Live Dealer'],
    tags: ['baccarat', 'live', 'gold', 'endorphina'],
    description:
      'Endorphina Baccarat Gold — premium baccarat with gold card effects and no commission on Banker.',
    featured: false,
    popular: true,
    new: true,
  },
  {
    id: 'endorphina-blackjack-vip',
    name: 'Endorphina Blackjack VIP Room',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '👑',
    rtp: '99.5%',
    volatility: 'low',
    minBet: 50,
    maxBet: 25000,
    features: ['VIP Room', 'High Limits', 'Premium Dealer'],
    tags: ['blackjack', 'live', 'vip', 'endorphina'],
    description:
      'Endorphina Blackjack VIP Room — exclusive high-limit blackjack with premium dealer experience.',
    featured: true,
    popular: false,
    new: true,
  },

  // ── Instant ──────────────────────────────────────────────
  {
    id: 'crash-pro',
    name: 'Crash Pro',
    category: 'instant',
    studio: 'pulse',
    glyph: '🚀',
    rtp: '96.0%',
    volatility: 'very-high',
    minBet: 0.1,
    maxBet: 25000,
    features: ['Auto Cashout', 'Dual Bet', 'Turbo Mode', 'Provably Fair'],
    tags: ['crash', 'multiplier', 'instant', 'live'],
    description:
      'Cash out before the curve breaks. Dual simultaneous bets, configurable auto-cashout, turbo rounds and a verifiable HMAC crash point.',
    featured: true,
    popular: true,
    new: false,
  },
  {
    id: 'lightning-dice',
    name: 'Lightning Dice',
    category: 'instant',
    studio: 'pulse',
    glyph: '⚡',
    rtp: '96.0%',
    volatility: 'very-high',
    minBet: 0.1,
    maxBet: 10000,
    features: ['Lightning Multipliers', 'Three Dice Totals', 'Provably Fair'],
    tags: ['dice', 'lightning', 'instant', 'multiplier'],
    description:
      'Three dice totals with lightning strikes boosting selected numbers up to 100×. Provably fair instant dice game with dynamic multipliers.',
    featured: true,
    popular: true,
    new: false,
  },
  {
    id: 'plinko-master',
    name: 'Plinko Master',
    category: 'instant',
    studio: 'pulse',
    glyph: '🔻',
    rtp: '97.0%',
    volatility: 'variable',
    minBet: 0.1,
    maxBet: 10000,
    features: ['Risk Levels', 'Row Selection', 'Real-time Physics'],
    tags: ['plinko', 'drop', 'multiplier', 'instant'],
    description:
      'Drop a ball through a peg field into a weighted bucket row. Three risk profiles and selectable row counts reshape the payout curve.',
    featured: false,
    popular: true,
  },
  {
    id: 'wheel-of-fortune',
    name: 'Fortune Wheel',
    category: 'instant',
    studio: 'pulse',
    glyph: '🎡',
    rtp: '96.0%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 10000,
    features: ['Provably Fair'],
    tags: ['instant', 'instant'],
    description: 'Fortune Wheel — Provably fair instant game.',
    featured: false,
    popular: true,
  },
  {
    id: 'lightning-roulette-pro',
    name: 'Lightning Roulette Pro',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '⚡',
    rtp: '97.0%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 10000,
    features: ['Provably Fair','Live Dealer'],
    tags: ['roulette,lightning,evolution'],
    description: 'Premium lightning roulette with multipliers up to x500.',
    featured: true,
    popular: true,
    new: false,
  },
  {
    id: 'crazy-time-v2',
    name: 'Crazy Time V2',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🎡',
    rtp: '97.0%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 10000,
    features: ['Provably Fair','Live Dealer'],
    tags: ['game-show,crazy-time'],
    description: 'Next-gen Crazy Time with bonus rounds.',
    featured: true,
    popular: true,
    new: false,
  },
  {
    id: 'crazy-time-pro',
    name: 'Crazy Time Pro',
    category: 'live-casino',
    studio: 'vertex',
    glyph: '🎡',
    rtp: '97.0%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 10000,
    features: ['Provably Fair','Live Dealer'],
    tags: ['game-show,crazy-time,evolution'],
    description: 'Enhanced Crazy Time game show experience.',
    featured: true,
    popular: true,
    new: false,
  },
  {
    id: 'mines-premium',
    name: 'Mines Premium',
    category: 'instant',
    studio: 'vertex',
    glyph: '💎',
    rtp: '97.0%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 10000,
    features: ['Provably Fair','Live Dealer'],
    tags: ['mines,instant'],
    description: 'Premium minesweeper-style game with multipliers.',
    featured: true,
    popular: true,
  },
  {
    id: 'fishing-tank',
    name: 'Fishing Tank',
    category: 'instant',
    studio: 'pulse',
    glyph: '🐟',
    rtp: '96.0%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 5000,
    features: ['Multiplier Cashout','Live Bots'],
    tags: ['fish,shark,ocean,155'],
    description: 'Fish swim in the tank but a shark approaches! Multiplier grows until danger.',
    featured: true,
    popular: true,
    new: true,
  },
  {
    id: 'snow-run',
    name: 'Snow Run',
    category: 'instant',
    studio: 'pulse',
    glyph: '⛷️',
    rtp: '96.0%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 5000,
    features: ['Multiplier Cashout','Live Bots'],
    tags: ['ski,race,mountain,155'],
    description: 'Skiers race downhill with growing multiplier. Cash out before the crash!',
    featured: true,
    popular: true,
    new: true,
  },
  {
    id: 'duck-race',
    name: 'Duck Race',
    category: 'instant',
    studio: 'pulse',
    glyph: '🦆',
    rtp: '96.0%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 5000,
    features: ['Multiplier Cashout','Live Bots'],
    tags: ['race,duck,racing,155'],
    description: 'Pick a duck and race to the finish! Multiplier grows as ducks swim.',
    featured: true,
    popular: true,
    new: true,
  },
  {
    id: 'footfall',
    name: 'FootFall',
    category: 'instant',
    studio: 'pulse',
    glyph: '👣',
    rtp: '96.0%',
    volatility: 'medium',
    minBet: 1,
    maxBet: 5000,
    features: ['Multiplier Cashout','Live Bots'],
    tags: ['cashout,multiplier,155'],
    description: 'Multiplier climbs until Footfall strikes! Cash out before it hits.',
    featured: true,
    popular: true,
    new: true,
  },
];

// ═══════════════════════════════════════════════════════════
// DERIVED VIEWS
// ═══════════════════════════════════════════════════════════

/** Rich record → lobby card shape consumed by the storefront UI. */
function toCard(g) {
  const cat = CATEGORY_BY_ID[g.category];
  const studio = STUDIOS[g.studio];
  return {
    id: g.id,
    title: g.name,
    icon: g.glyph,
    hue: cat.hue,
    category: cat.label,
    studio: g.author || studio.name,
    rating: g.rating ?? (g.rtp ? DERIVE.ratingFromRtp(g.rtp) : DERIVE.defaultRating),
    hot: Boolean(g.popular),
    new: Boolean(g.new),
    url: `${DERIVE.gameBasePath}/${g.id}/index.html`,
    cover: DERIVE.coverPath(g.id),
    license: g.license || (studio.inHouse ? LICENSES.inHouse : LICENSES.mit),
    rtp: g.rtp || null,
    volatility: g.volatility || null,
    features: g.features || [],
    description: g.description,
  };
}

/** Lobby card list. */
const games = GAMES.map(toCard);

/** Filter chips: virtual filters first, then real categories. */
const categories = [...VIRTUAL_CATEGORIES, ...CATEGORIES.map((c) => c.label)];

// ─── Lookups ────────────────────────────────────────────────

function getGameById(id) {
  return GAMES.find((g) => g.id === id);
}

function getGamesByCategory(categoryId) {
  if (!categoryId || categoryId === 'all') return GAMES;
  return GAMES.filter((g) => g.category === categoryId);
}

function searchGames(query) {
  const q = String(query || '').toLowerCase().trim();
  if (!q) return GAMES;
  return GAMES.filter(
    (g) =>
      g.name.toLowerCase().includes(q) ||
      (g.description || '').toLowerCase().includes(q) ||
      (g.tags || []).some((t) => t.includes(q)) ||
      (STUDIOS[g.studio]?.name || '').toLowerCase().includes(q),
  );
}

function getGameStats() {
  return {
    total: GAMES.length,
    byCategory: Object.fromEntries(
      CATEGORIES.map((c) => [c.id, GAMES.filter((g) => g.category === c.id).length]),
    ),
    featured: GAMES.filter((g) => g.featured).length,
    popular: GAMES.filter((g) => g.popular).length,
    new: GAMES.filter((g) => g.new).length,
  };
}

export {
  GAMES,
  CATEGORIES,
  VIRTUAL_CATEGORIES,
  STUDIOS,
  LICENSES,
  VOLATILITY,
  games,
  categories,
  toCard,
  getGameById,
  getGamesByCategory,
  searchGames,
  getGameStats,
};
